# Generated by Django 5.1.1 on 2026-06-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
