# Generated by Django 5.1.1 on 2026-06-08 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_bio_profile_email_verified_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='invite_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
