# Generated by Django 5.1.1 on 2026-06-08 11:38

from django.db import migrations
import uuid


def normalize_invite_codes(apps, schema_editor):
    Room = apps.get_model('home', 'Room')
    seen = set()
    for room in Room.objects.order_by('id'):
        code = str(room.invite_code)
        if not code or code in seen:
            room.invite_code = uuid.uuid4()
            room.save(update_fields=['invite_code'])
            code = str(room.invite_code)
        seen.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_room_cover_room_invite_code_room_is_private'),
    ]

    operations = [
        migrations.RunPython(normalize_invite_codes, migrations.RunPython.noop),
    ]
