# Generated by Django 5.1.1 on 2026-06-10 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='home_messag_room_id_a416c8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', '-created_at'], name='home_messag_user_id_31fc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_private', '-updated_at'], name='home_room_is_priv_ea01cc_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['topic', '-updated_at'], name='home_room_topic_i_651fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['host', '-updated_at'], name='home_room_host_id_6dce62_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='home_topic_name_248578_idx'),
        ),
    ]
